### ISSUE TITLE
pipe

### ISSUE THREAD

**Issue by Raynos** [Gozala/reducers#14]
https://github.com/Raynos/reflex-todo/blob/master/lib/pipe.js

**Comment by Gozala** [comment]
Close but not quite. It does not propagates erros, it should I think.

**Comment by Raynos** [comment]
That depends.

promises propagate errors by saying `pipe(a, b)` means if a errors then emit error on b.

domains handle errors by saying `pipe(a, b)` a and b are now on the domain, errors go to that domain.

Not sure which is a better error handling model.

**Comment by Gozala** [comment]
I was thinking in terms of propagating errors from `a` to `b`. That way you don't need domain, it's just you put a `capture(stream, handle)` wherever you need to handle errors.

**Comment by Raynos** [comment]
that works good enough for me.

**Comment by Gozala** [comment]
If you'll send in pull request with implementation I'll gladly accept. Otherwise I'll have it in by Monday ;)
