### ISSUE TITLE
ES6 Module transpiler

### ISSUE THREAD

**Issue by gordonbrander** [Gozala/reducers#53]
Any interest in switching module definitions in the source to ES6 Modules? Doing so would allow the [ES6 module transpiler](https://github.com/umdjs/es6-module-transpiler) to produce CommonJS and AMD versions of the source. Everyone is happy!

**Comment by Raynos** [comment]
browserify can already transpile commonJS into AMD.

**Comment by gordonbrander** [comment]
Here's why I think this is cool:
- You can compile browser version that exports to globals.
- Compiled source looks like the source you would write by hand in each case.
- You can keep compiled files separate --- no need to glom them into one file.
- Use whatever bundling toolchain you are familiar with. It lets library consumers use the tools and workflow they would use otherwise, instead of asking them learn a new tool.
- ES6 module syntax is pretty.

**Comment by gordonbrander** [comment]
Hmm, I retract my support. ES6 Module transpiler currently only supports declarations with semicolons at the end. Don't want to poison reducer's oh-so-lovely comma-free hipster style! Maybe someday...
