### ISSUE TITLE
Uncaught Error: define cannot be used indirect

### ISSUE THREAD

**Issue by vvetsko** [Gozala/reducers#54]
I am trying to use reducer with redux and cannot run application because I am getting next error in browser "Uncaught Error: define cannot be used indirect".
Looks  like error in reduce.js from reducible package
using webpack:1.12.2

**Comment by indiejoseph** [comment]
@bigset1 how did you solved the problem?

**Comment by Gozala** [comment]
That must be webpack related issue, as it works fine in node and this package has not `reduce.js` file at all.

**Comment by indrasantosa** [comment]
Have anyone found a solution? is upgrading the webpack will solve the problem?

**Comment by vvetsko** [comment]
Updating to webpack 2 solved this problem
