### ISSUE TITLE
No docs

### ISSUE THREAD

**Issue by Raynos** [Gozala/reducers#8]
-.-

**Comment by Gozala** [comment]
There are bunch of inline docs you can take a look at: https://github.com/Gozala/reducers/blob/master/core.js
You can also take a look at idea walkthrough: https://gist.github.com/2656978

I know it's not perfect, but I'm planning on writing proper docs at some point.

**Comment by Gozala** [comment]
Docs have being added!

**Comment by Raynos** [comment]
Can we have docs for each individual function somewhere that is not embedded in the code.

Then either have it in README or add a link to the docs from README

**Comment by Gozala** [comment]
I'm actually working on doc generator, thats why my new projects are around
ast analyzes. If you wish to get something in theeantime I'm happy to get a
pull request

Or page on a wiki...

On Thursday, January 3, 2013, Raynos wrote:

> Can we have docs for each individual function somewhere that is not
> embedded in the code.
> 
> Then either have it in README or add a link to the docs from README
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Gozala/reducers/issues/8#issuecomment-11870804.

## 

Typed on tiny virtual keyboard

**Comment by Raynos** [comment]
Oh sweet!
