### ISSUE TITLE
No main field, no index.js

### ISSUE THREAD

**Issue by Raynos** [Gozala/reducers#9]
What is the entry point?

**Comment by Gozala** [comment]
That is because there is no `main` :) so `core.js` is core that everything else uses, but it's really has no main.

**Comment by gordonbrander** [comment]
While its true that this is just a collection of libraries, after working with it, I think it would be helpful to have an index.js that gives you accumulator.js and core.js.

**Comment by Gozala** [comment]
Fixed in 0.1.6
